# .goreleaser.yml
project_name: serpent

# Changelog Configuration
changelog:
  sort: desc
  filters:
    exclude:
      - '^Merge pull request'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation Updates"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other Changes"
      regexp: "^(ci|build|misc|perf|deps):"
      order: 3
    - title: "Miscellaneous"
      regexp: ".*"
      order: 4

builds:
  - id: "serpent"
    binary: serpent
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64

archives:
  - id: "archive"
    builds:
      - serpent
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

# Release configuration
release:
  github:
    owner: deggja
    name: serpent
  draft: false
